package com.dooglemaps.route;

import com.dooglemaps.data.FarmPatch;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import javax.annotation.Nullable;

/**
 * Every patch's real position and footprint, measured from a live client.
 *
 * <h2>Measured, not hand-authored — which is the whole point</h2>
 *
 * {@link PatchLocationStore}'s class note explains why positions were learned rather than listed:
 * RuneLite's farming data identifies a patch by region and varbit and never needs to walk
 * anywhere, so there is no coordinate table to mirror, and <i>"hand-authoring 107 of them would
 * be a lot of data to get subtly wrong and then maintain"</i>.
 *
 * <p>That was a good reason while nothing could measure them. The plugin measures them now. Every
 * entry below was read off the client by standing next to the patch and watching its game objects
 * spawn — the same {@code PatchLocationCapture} path that fills the per-profile store — and then
 * dumped out of a profile that had visited all 107. Nobody typed a coordinate.
 *
 * <h2>Why it is worth having at all, when the store already learns them</h2>
 *
 * Because the store learns them <b>per RuneScape profile</b>, so every account starts blind and
 * relearns the same immutable facts. A patch's position is a fact about the game world, not about
 * an account. Baked in, every account has all of it from first launch; the learned store keeps
 * working on top as a self-correcting refinement, and wins wherever it has something.
 *
 * <p>What that buys, concretely: within a stop, patches are ordered nearest-first, and that needs
 * each to have its own coordinate. {@code WikiPatchLocations} publishes one pin per <i>location</i>
 * — the wiki's own granularity — so every patch in a region returned the identical point, compared
 * equal, and the order collapsed to declaration order. The Hosidius vinery is the extreme: twelve
 * grape patches on one pin, now twelve positions one to thirteen tiles apart.
 *
 * <h2>The shape, and the hespori</h2>
 *
 * {@code {x, y, plane, sizeX, sizeY, swX, swY}} — the same seven the learned store uses. The point
 * is a tile the patch <b>occupies</b> and the corner plus size is its extent; the two are separate
 * because patches are frequently not rectangles. See {@code PatchLocationStore.record}.
 *
 * <p>The hespori is included and is <b>known to be wrong</b>. Its patch is in an instanced cave, so
 * the coordinate read there is instance-space and means nothing on the world map. It is harmless
 * because it is never served: {@code PatchLocationStore.getLocation} answers the hespori with the
 * cave's overworld <i>entrance</i> before consulting any tier, and {@code record} refuses to learn
 * it, for the same reason this row cannot be trusted. The row stays so the table is the complete
 * measured set rather than the set minus one unexplained gap — and so a regeneration, which walks
 * every patch and dumps what it saw, does not look like it lost one.
 *
 * <h2>Regenerating</h2>
 *
 * Visit every patch with the plugin running, then dump the profile's {@code patchLocations} blob.
 * It is not generated by a script in {@code tools/} because it is not derived from anything —
 * it is an observation, and the observation costs about two and a half hours of walking.
 */
public final class MeasuredPatchLocations
{
	private static final Map<String, int[]> MEASURED = measured();

	private static Map<String, int[]> measured()
	{
		Map<String, int[]> m = new HashMap<>();


		// Al Kharid
		m.put("13106.4771", new int[]{3315, 3202, 0, 2, 2, 3315, 3202});  // cactus

		// Aldarin
		m.put("5421.4771", new int[]{1364, 2938, 0, 4, 4, 1363, 2937});  // hops

		// Anglers' Retreat
		m.put("9770.4771", new int[]{2471, 2703, 0, 3, 3, 2470, 2702});  // hardwood_tree

		// Ardougne
		m.put("10290.4771", new int[]{2617, 3225, 0, 2, 2, 2617, 3225});  // bush
		m.put("10548.4771", new int[]{2664, 3378, 0, 10, 3, 2662, 3377});  // allotment
		m.put("10548.4772", new int[]{2664, 3371, 0, 10, 3, 2662, 3370});  // allotment
		m.put("10548.4773", new int[]{2666, 3374, 0, 2, 2, 2666, 3374});  // flower
		m.put("10548.4774", new int[]{2670, 3374, 0, 2, 2, 2670, 3374});  // herb
		m.put("10548.4775", new int[]{2661, 3375, 0, 1, 1, 2661, 3375});  // compost

		// Auburnvale
		m.put("5427.4771", new int[]{1366, 3321, 0, 3, 3, 1365, 3320});  // tree
		m.put("5427.4772", new int[]{1450, 3354, 0, 1, 1, 1450, 3354});  // belladonna

		// Avium Savannah
		m.put("6702.4771", new int[]{1687, 2972, 0, 3, 3, 1686, 2971});  // hardwood_tree

		// Brimhaven
		m.put("11058.4771", new int[]{2764, 3212, 0, 2, 2, 2764, 3212});  // fruit_tree
		m.put("11058.4772", new int[]{2802, 3203, 0, 3, 3, 2801, 3202});  // spirit_tree

		// Catherby
		m.put("11062.4771", new int[]{2809, 3467, 0, 10, 3, 2805, 3466});  // allotment
		m.put("11062.4772", new int[]{2809, 3460, 0, 10, 3, 2805, 3459});  // allotment
		m.put("11062.4773", new int[]{2809, 3463, 0, 2, 2, 2809, 3463});  // flower
		m.put("11062.4774", new int[]{2813, 3463, 0, 2, 2, 2813, 3463});  // herb
		m.put("11062.4775", new int[]{2804, 3464, 0, 1, 1, 2804, 3464});  // compost
		m.put("11317.4771", new int[]{2860, 3433, 0, 2, 2, 2860, 3433});  // fruit_tree

		// Champions' Guild
		m.put("12596.4771", new int[]{3181, 3357, 0, 2, 2, 3181, 3357});  // bush

		// Civitas illa Fortis
		m.put("6192.4771", new int[]{1582, 3100, 0, 5, 6, 1581, 3098});  // allotment
		m.put("6192.4772", new int[]{1587, 3095, 0, 6, 5, 1585, 3094});  // allotment
		m.put("6192.4773", new int[]{1585, 3098, 0, 2, 2, 1585, 3098});  // flower
		m.put("6192.4774", new int[]{1581, 3094, 0, 2, 2, 1581, 3094});  // herb
		m.put("6192.4775", new int[]{1588, 3103, 0, 1, 1, 1588, 3103});  // compost

		// Draynor Manor
		m.put("12340.4771", new int[]{3086, 3354, 0, 2, 2, 3086, 3354});  // belladonna

		// Entrana
		m.put("11060.4771", new int[]{2811, 3336, 0, 4, 4, 2809, 3335});  // hops

		// Etceteria
		m.put("10300.4771", new int[]{2591, 3863, 0, 2, 2, 2591, 3863});  // bush
		m.put("10300.4772", new int[]{2613, 3858, 0, 3, 3, 2612, 3857});  // spirit_tree

		// Falador
		m.put("11828.4771", new int[]{3004, 3373, 0, 3, 3, 3003, 3372});  // tree
		m.put("12083.4771", new int[]{3051, 3309, 0, 5, 6, 3050, 3307});  // allotment
		m.put("12083.4772", new int[]{3057, 3304, 0, 5, 6, 3055, 3303});  // allotment
		m.put("12083.4773", new int[]{3054, 3307, 0, 2, 2, 3054, 3307});  // flower
		m.put("12083.4774", new int[]{3058, 3311, 0, 2, 2, 3058, 3311});  // herb
		m.put("12083.4775", new int[]{3056, 3312, 0, 1, 1, 3056, 3312});  // compost

		// Farming Guild
		m.put("4922.4771", new int[]{1253, 3750, 0, 3, 3, 1252, 3749});  // spirit_tree
		m.put("4922.4772", new int[]{1260, 3733, 0, 2, 2, 1260, 3733});  // bush
		m.put("4922.4773", new int[]{1268, 3734, 0, 6, 5, 1267, 3732});  // allotment
		m.put("4922.4774", new int[]{1268, 3725, 0, 6, 5, 1267, 3723});  // allotment
		m.put("4922.4775", new int[]{1238, 3726, 0, 2, 2, 1238, 3726});  // herb
		m.put("4922.7904", new int[]{1264, 3747, 0, 2, 2, 1264, 3747});  // cactus
		m.put("4922.7905", new int[]{1232, 3736, 0, 3, 3, 1231, 3735});  // tree
		m.put("4922.7906", new int[]{1260, 3725, 0, 2, 2, 1260, 3725});  // flower
		m.put("4922.7907", new int[]{1228, 3754, 0, 8, 8, 1225, 3751});  // redwood
		m.put("4922.7909", new int[]{1242, 3758, 0, 2, 2, 1242, 3758});  // fruit_tree
		m.put("4922.7910", new int[]{1244, 3750, 0, 3, 3, 1243, 3749});  // celastrus
		m.put("4922.7911", new int[]{1232, 3723, 0, 3, 3, 1231, 3722});  // anima
		m.put("4922.7912", new int[]{1272, 3729, 0, 2, 2, 1272, 3729});  // big_compost
		m.put("5021.7908", new int[]{1247, 10087, 0, 3, 3, 1246, 10086});  // hespori

		// Fossil Island
		m.put("14651.4771", new int[]{3715, 3835, 0, 3, 3, 3714, 3834});  // hardwood_tree
		m.put("14651.4772", new int[]{3708, 3833, 0, 3, 3, 3707, 3832});  // hardwood_tree
		m.put("14651.4773", new int[]{3702, 3837, 0, 3, 3, 3701, 3836});  // hardwood_tree

		// Gnome Stronghold
		m.put("9781.4771", new int[]{2436, 3415, 0, 3, 3, 2435, 3414});  // tree
		m.put("9781.4772", new int[]{2475, 3445, 0, 2, 2, 2475, 3445});  // fruit_tree

		// Great Conch
		m.put("12581.4771", new int[]{3299, 8860, 1, 2, 2, 3299, 8860});  // coral
		m.put("12581.4772", new int[]{3294, 8860, 1, 2, 2, 3294, 8860});  // coral
		m.put("12581.4773", new int[]{3128, 2405, 0, 3, 3, 3127, 2404});  // calquat

		// Harmony
		m.put("15148.4771", new int[]{3794, 2833, 0, 1, 6, 3794, 2833});  // allotment
		m.put("15148.4772", new int[]{3789, 2837, 0, 2, 2, 3789, 2837});  // herb

		// Kastori
		m.put("5423.4771", new int[]{1367, 3032, 0, 3, 3, 1366, 3031});  // calquat
		m.put("5423.4772", new int[]{1349, 3056, 0, 2, 2, 1349, 3056});  // fruit_tree
		m.put("5423.4773", new int[]{1352, 3022, 0, 2, 2, 1352, 3022});  // flower

		// Kourend
		m.put("6967.4771", new int[]{1736, 3558, 0, 7, 6, 1733, 3554});  // allotment
		m.put("6967.4772", new int[]{1731, 3552, 0, 6, 6, 1730, 3550});  // allotment
		m.put("6967.4773", new int[]{1734, 3554, 0, 2, 2, 1734, 3554});  // flower
		m.put("6967.4774", new int[]{1738, 3550, 0, 2, 2, 1738, 3550});  // herb
		m.put("6967.4775", new int[]{1730, 3558, 0, 1, 1, 1730, 3558});  // compost
		m.put("6967.7904", new int[]{1693, 3542, 0, 3, 3, 1692, 3541});  // spirit_tree
		m.put("7223.4953", new int[]{1808, 3562, 0, 1, 1, 1808, 3562});  // grapes
		m.put("7223.4954", new int[]{1808, 3560, 0, 1, 1, 1808, 3560});  // grapes
		m.put("7223.4955", new int[]{1808, 3558, 0, 1, 1, 1808, 3558});  // grapes
		m.put("7223.4956", new int[]{1808, 3553, 0, 1, 1, 1808, 3553});  // grapes
		m.put("7223.4957", new int[]{1808, 3551, 0, 1, 1, 1808, 3551});  // grapes
		m.put("7223.4958", new int[]{1808, 3549, 0, 1, 1, 1808, 3549});  // grapes
		m.put("7223.4959", new int[]{1807, 3562, 0, 1, 1, 1807, 3562});  // grapes
		m.put("7223.4960", new int[]{1807, 3560, 0, 1, 1, 1807, 3560});  // grapes
		m.put("7223.4961", new int[]{1807, 3558, 0, 1, 1, 1807, 3558});  // grapes
		m.put("7223.4962", new int[]{1807, 3553, 0, 1, 1, 1807, 3553});  // grapes
		m.put("7223.4963", new int[]{1807, 3551, 0, 1, 1, 1807, 3551});  // grapes
		m.put("7223.4964", new int[]{1807, 3549, 0, 1, 1, 1807, 3549});  // grapes

		// Lletya
		m.put("9265.4771", new int[]{2346, 3161, 0, 2, 2, 2346, 3161});  // fruit_tree

		// Lumbridge
		m.put("12594.4771", new int[]{3193, 3231, 0, 3, 3, 3192, 3230});  // tree
		m.put("12851.4771", new int[]{3229, 3315, 0, 5, 5, 3227, 3313});  // hops

		// Morytania
		m.put("13622.4771", new int[]{3451, 3472, 0, 2, 2, 3451, 3472});  // mushroom
		m.put("14391.4771", new int[]{3598, 3527, 0, 5, 6, 3597, 3525});  // allotment
		m.put("14391.4772", new int[]{3604, 3522, 0, 5, 6, 3602, 3521});  // allotment
		m.put("14391.4773", new int[]{3601, 3525, 0, 2, 2, 3601, 3525});  // flower
		m.put("14391.4774", new int[]{3605, 3529, 0, 2, 2, 3605, 3529});  // herb
		m.put("14391.4775", new int[]{3610, 3522, 0, 1, 1, 3610, 3522});  // compost

		// Port Sarim
		m.put("12082.4771", new int[]{3060, 3258, 0, 3, 3, 3059, 3257});  // spirit_tree

		// Prifddinas
		m.put("13151.4771", new int[]{3289, 6102, 0, 6, 4, 3288, 6101});  // allotment
		m.put("13151.4772", new int[]{3290, 6096, 0, 6, 4, 3288, 6095});  // allotment
		m.put("13151.4773", new int[]{3292, 6099, 0, 2, 2, 3292, 6099});  // flower
		m.put("13151.4774", new int[]{3287, 6100, 0, 1, 1, 3287, 6100});  // compost
		m.put("13151.4775", new int[]{3291, 6118, 0, 2, 2, 3291, 6118});  // crystal_tree

		// Rimmington
		m.put("11570.4771", new int[]{2940, 3221, 0, 2, 2, 2940, 3221});  // bush

		// Seaweed
		m.put("15008.4771", new int[]{3733, 10273, 1, 2, 2, 3733, 10273});  // seaweed
		m.put("15008.4772", new int[]{3733, 10267, 1, 2, 2, 3733, 10267});  // seaweed

		// Seers' Village
		m.put("10551.4771", new int[]{2665, 3525, 0, 6, 6, 2664, 3523});  // hops

		// Tai Bwo Wannai
		m.put("11056.4771", new int[]{2796, 3101, 0, 3, 3, 2795, 3100});  // calquat

		// Taverley
		m.put("11573.4771", new int[]{2936, 3438, 0, 3, 3, 2935, 3437});  // tree

		// Tree Gnome Village
		m.put("9777.4771", new int[]{2489, 3179, 0, 2, 2, 2489, 3179});  // fruit_tree

		// Troll Stronghold
		m.put("11321.4771", new int[]{2826, 3694, 0, 2, 2, 2826, 3694});  // herb

		// Varrock
		m.put("12854.4771", new int[]{3229, 3459, 0, 3, 3, 3228, 3458});  // tree

		// Weiss
		m.put("11325.4771", new int[]{2848, 3934, 0, 2, 2, 2848, 3934});  // herb

		// Yanille
		m.put("10288.4771", new int[]{2575, 3104, 0, 4, 4, 2574, 3103});  // hops

		return Collections.unmodifiableMap(m);
	}

	private MeasuredPatchLocations()
	{
	}

	/**
	 * This patch's measured position and extent, or null when it was never observed.
	 *
	 * <p>The array is copied on the way out. It is handed to callers that read it positionally and
	 * a shared mutable one is a table that can be edited by accident.
	 */
	@Nullable
	public static int[] forPatch(FarmPatch patch)
	{
		int[] measured = MEASURED.get(patch.getKey());
		return measured == null ? null : measured.clone();
	}

	/** How many patches the table covers, for the tests that pin it against the world data. */
	public static int size()
	{
		return MEASURED.size();
	}
}
